def generate_analysis_pdf_html(analysis):
    """
    Generates a printable HTML report for an Analysis.
    """
    matched = analysis.analysis_skills.filter(status='matched')
    partial = analysis.analysis_skills.filter(status='partial')
    missing = analysis.analysis_skills.filter(status='missing')
    
    html = f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>SkillBridge Career Intelligence Report - {analysis.job_description.title}</title>
    <style>
      @page {{
        size: A4;
        margin: 20mm;
      }}
      body {{
        font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
        color: #1a1a1a;
        line-height: 1.5;
        font-size: 13px;
      }}
      .header {{
        border-bottom: 2px solid #565449;
        padding-bottom: 12px;
        margin-bottom: 24px;
        display: flex;
        justify-content: space-between;
        align-items: center;
      }}
      .title {{
        font-size: 24px;
        font-weight: bold;
        color: #11120d;
        margin: 0;
      }}
      .badge {{ padding: 6px 14px; background: #D8CFBC; border-radius: 20px; font-weight: bold; font-size: 14px; }}
        .score-box {{ text-align: center; background: #FFFBF4; border: 2px solid #D8CFBC; border-radius: 12px; padding: 20px; margin-bottom: 30px; }}
        .score-num {{ font-size: 48px; font-weight: bold; color: #11120D; margin: 0; }}
        .section-title {{ font-size: 18px; border-bottom: 1px solid #ccc; padding-bottom: 6px; margin-top: 30px; color: #565449; }}
        .skill-tag {{ display: inline-block; padding: 4px 10px; background: #e2e8f0; border-radius: 6px; font-size: 12px; margin: 3px; font-weight: 600; }}
        .matched {{ background: #d1fae5; color: #065f46; }}
        .missing {{ background: #fee2e2; color: #991b1b; }}
    </style>
</head>
<body>
    <div class="header">
        <div>
            <h1 class="title">SkillBridge Career Report</h1>
            <p>Target Role: <strong>{analysis.job_description.title}</strong> | Candidate: <strong>{analysis.user.username}</strong></p>
        </div>
        <span class="badge">{analysis.get_score_label()}</span>
    </div>

    <div class="score-box">
        <div class="score-num">{analysis.readiness_score} / 100</div>
        <p>Estimated Job Readiness Score based on skill coverage & evidence</p>
    </div>

    <div class="section-title">Executive Summary</div>
    <p>{analysis.summary}</p>

    <div class="section-title">Matched Skills ({matched.count()})</div>
    <div>
        {"".join([f'<span class="skill-tag matched">✓ {s.skill.name}</span>' for s in matched])}
    </div>

    <div class="section-title">Critical Skill Gaps ({missing.count()})</div>
    <div>
        {"".join([f'<div style="margin-bottom:8px;"><strong>⚠ {s.skill.name}</strong> (Priority {s.priority}): {s.recommendation}</div>' for s in missing])}
    </div>

    <div style="margin-top: 40px; font-size: 11px; text-align: center; color: #777;">
        Report generated by SkillBridge Platform on {analysis.created_at.strftime('%B %d, %Y')}
    </div>
</body>
</html>
"""
    return html
