# Generated by Django 6.0.7 on 2026-08-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillbridge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='resource_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='resource_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
